// Auto generated file
export default {
  "website": {
    "name": "website",
    "description": "My website made with ❤️",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/website"
  },
  "uno-slash-website": {
    "name": "uno-slash-website",
    "description": "website made especially for my bot UnoSlash",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/uno-slash-website"
  },
  "snakegame": {
    "name": "snakegame",
    "description": "A classic snake game made with go",
    "language": "Go",
    "href": "https://github.com/vitoUwu/snakegame"
  },
  "ban-remover": {
    "name": "ban-remover",
    "description": null,
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/ban-remover"
  },
  "uno-slash": {
    "name": "uno-slash",
    "description": "A simple bot made to bring entertainment to your server",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/uno-slash"
  },
  "discord-id-formatter": {
    "name": "discord-id-formatter",
    "description": "A simple website designed to help Discord communities by formatting the logs generated by bots, making it easier to identify and punish IDs",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/discord-id-formatter"
  },
  "ban-remover-rs": {
    "name": "ban-remover-rs",
    "description": "A discord bot made with rust to unban users from your guild",
    "language": "Rust",
    "href": "https://github.com/vitoUwu/ban-remover-rs"
  },
  "sistema-bancario": {
    "name": "sistema-bancario",
    "description": "Atividade do módulo 4 do curso de Engenharia de Software, disciplina de Linguagens e Técnicas de Programação",
    "language": "C",
    "href": "https://github.com/vitoUwu/sistema-bancario"
  },
  "vue-components": {
    "name": "vue-components",
    "description": "Some UI tests and animations done with vue.js and tailwind.",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/vue-components"
  },
  "PassIn": {
    "name": "PassIn",
    "description": "A backend for an event creation application",
    "language": "C#",
    "href": "https://github.com/vitoUwu/PassIn"
  },
  "FileUploader": {
    "name": "FileUploader",
    "description": "A file uploader API made with ASP.NET ",
    "language": "C#",
    "href": "https://github.com/vitoUwu/FileUploader"
  },
  "WebApi": {
    "name": "WebApi",
    "description": "An API made for studies on the C# and .NET 8",
    "language": "C#",
    "href": "https://github.com/vitoUwu/WebApi"
  },
  "vitoUwu": {
    "name": "vitoUwu",
    "description": null,
    "language": null,
    "href": "https://github.com/vitoUwu/vitoUwu"
  },
  "Airhorn": {
    "name": "Airhorn",
    "description": "A Discord bot made with go",
    "language": "Go",
    "href": "https://github.com/vitoUwu/Airhorn"
  },
  "memonote": {
    "name": "memonote",
    "description": "Memonote is an app designed for people who are brilliant. Write down your ideas, stories, checklists and have everything synced",
    "language": "Svelte",
    "href": "https://github.com/vitoUwu/memonote"
  },
  "notification-service": {
    "name": "notification-service",
    "description": null,
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/notification-service"
  },
  "FSMP": {
    "name": "FSMP",
    "description": "A Discord bot used in a private server to display informations about a minecraft server",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/FSMP"
  },
  "NamedVillagers": {
    "name": "NamedVillagers",
    "description": "A simple spigot plugin that generate names for villagers and announce when they dies",
    "language": "Java",
    "href": "https://github.com/vitoUwu/NamedVillagers"
  },
  "go-api": {
    "name": "go-api",
    "description": "Study purpose repo",
    "language": "Go",
    "href": "https://github.com/vitoUwu/go-api"
  },
  "tiny-tales": {
    "name": "tiny-tales",
    "description": "Tiny Tales is a place where you can post tiny texts.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/tiny-tales"
  },
  "boracodar": {
    "name": "boracodar",
    "description": "Toda quarta-feira um novo desafio é lançado, nesse evento são apresentadas propostas de projetos toda semana para praticarmos e aprimorarmos.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/boracodar"
  },
  "Flutter-Task-App": {
    "name": "Flutter-Task-App",
    "description": "A task app created with flutter",
    "language": "Dart",
    "href": "https://github.com/vitoUwu/Flutter-Task-App"
  },
  "Vitter": {
    "name": "Vitter",
    "description": "Vitter is an application inspired by Twitter.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/Vitter"
  },
  "copa-nlw": {
    "name": "copa-nlw",
    "description": "Copa NLW é um projeto desenvolvido no evento da Rocketseat, onde usamos Next.js, React Native e Typescript ",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/copa-nlw"
  },
  "what-to-watch": {
    "name": "what-to-watch",
    "description": "What to Watch é um site onde você pode encontrar filmes novos ou até mesmo lembrar de filmes antigos! Perfeito para pessoas indecisas que ainda não sabem o que assistir.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/what-to-watch"
  },
  "apuracoes-2022": {
    "name": "apuracoes-2022",
    "description": "Projeto feito para acompanhar as apurações das eleições brasileiras de 2022.",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/apuracoes-2022"
  },
  "ignite-lab-design-system": {
    "name": "ignite-lab-design-system",
    "description": " Um projeto desenvolvido nos 3 dias de evento do Ignite Lab 03 desenvolvido pela Rocketseat, onde o objetivo era aprender Design System, funcionalidades do Figma e do Storybook.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/ignite-lab-design-system"
  },
  "esports-nlw": {
    "name": "esports-nlw",
    "description": "Rocketseat | Next Level Week - React, React Native, TypeScript",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/esports-nlw"
  },
  "Discord-bot-template": {
    "name": "Discord-bot-template",
    "description": "Um simples template para criar bots no discord",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/Discord-bot-template"
  },
  "Python-TUI-Game": {
    "name": "Python-TUI-Game",
    "description": "A simple terminal-based game",
    "language": "Python",
    "href": "https://github.com/vitoUwu/Python-TUI-Game"
  }
};