// Auto generated file
export default {
  "deco-cx-apps": {
    "name": "deco-cx-apps",
    "description": "App definitions by deco.cx",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/deco-cx-apps",
    "isFork": true
  },
  "pilhas-em-c": {
    "name": "pilhas-em-c",
    "description": null,
    "language": "C",
    "href": "https://github.com/vitoUwu/pilhas-em-c",
    "isFork": false
  },
  "vitoUwu": {
    "name": "vitoUwu",
    "description": null,
    "language": null,
    "href": "https://github.com/vitoUwu/vitoUwu",
    "isFork": false
  },
  "website": {
    "name": "website",
    "description": "My website made with ❤️",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/website",
    "isFork": false
  },
  "ban-remover": {
    "name": "ban-remover",
    "description": null,
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/ban-remover",
    "isFork": false
  },
  "QuestsBot": {
    "name": "QuestsBot",
    "description": "A discord bot that add quests to your guild [WIP]",
    "language": "C#",
    "href": "https://github.com/vitoUwu/QuestsBot",
    "isFork": false
  },
  "NewTalents": {
    "name": "NewTalents",
    "description": null,
    "language": "C#",
    "href": "https://github.com/vitoUwu/NewTalents",
    "isFork": false
  },
  "trilha-net-testes-unitarios-desafio": {
    "name": "trilha-net-testes-unitarios-desafio",
    "description": null,
    "language": "C#",
    "href": "https://github.com/vitoUwu/trilha-net-testes-unitarios-desafio",
    "isFork": true
  },
  "trilha-net-api-desafio": {
    "name": "trilha-net-api-desafio",
    "description": null,
    "language": "C#",
    "href": "https://github.com/vitoUwu/trilha-net-api-desafio",
    "isFork": true
  },
  "trilha-net-banco-de-dados-desafio": {
    "name": "trilha-net-banco-de-dados-desafio",
    "description": null,
    "language": "TSQL",
    "href": "https://github.com/vitoUwu/trilha-net-banco-de-dados-desafio",
    "isFork": true
  },
  "trilha-net-poo-desafio": {
    "name": "trilha-net-poo-desafio",
    "description": null,
    "language": "C#",
    "href": "https://github.com/vitoUwu/trilha-net-poo-desafio",
    "isFork": true
  },
  "trilha-net-explorando-desafio": {
    "name": "trilha-net-explorando-desafio",
    "description": null,
    "language": "C#",
    "href": "https://github.com/vitoUwu/trilha-net-explorando-desafio",
    "isFork": true
  },
  "uno-slash-website": {
    "name": "uno-slash-website",
    "description": "website made especially for my bot UnoSlash",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/uno-slash-website",
    "isFork": false
  },
  "snakegame": {
    "name": "snakegame",
    "description": "A classic snake game made with go",
    "language": "Go",
    "href": "https://github.com/vitoUwu/snakegame",
    "isFork": false
  },
  "uno-slash": {
    "name": "uno-slash",
    "description": "A simple bot made to bring entertainment to your server",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/uno-slash",
    "isFork": false
  },
  "discord-id-formatter": {
    "name": "discord-id-formatter",
    "description": "A simple website designed to help Discord communities by formatting the logs generated by bots, making it easier to identify and punish IDs",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/discord-id-formatter",
    "isFork": false
  },
  "ban-remover-rs": {
    "name": "ban-remover-rs",
    "description": "A discord bot made with rust to unban users from your guild",
    "language": "Rust",
    "href": "https://github.com/vitoUwu/ban-remover-rs",
    "isFork": false
  },
  "sistema-bancario": {
    "name": "sistema-bancario",
    "description": "Atividade do módulo 4 do curso de Engenharia de Software, disciplina de Linguagens e Técnicas de Programação",
    "language": "C",
    "href": "https://github.com/vitoUwu/sistema-bancario",
    "isFork": false
  },
  "vue-components": {
    "name": "vue-components",
    "description": "Some UI tests and animations done with vue.js and tailwind.",
    "language": "Vue",
    "href": "https://github.com/vitoUwu/vue-components",
    "isFork": false
  },
  "PassIn": {
    "name": "PassIn",
    "description": "A backend for an event creation application",
    "language": "C#",
    "href": "https://github.com/vitoUwu/PassIn",
    "isFork": false
  },
  "trilha-net-fundamentos-desafio": {
    "name": "trilha-net-fundamentos-desafio",
    "description": "Desafio de projeto .NET Fundamentos - DIO",
    "language": "C#",
    "href": "https://github.com/vitoUwu/trilha-net-fundamentos-desafio",
    "isFork": true
  },
  "dio-lab-open-source": {
    "name": "dio-lab-open-source",
    "description": "⚠LEIA A ISSUE FIXADA! Repositório do lab Contribuindo em um Projeto Open Source no GitHub da Digital Innovation One.",
    "language": "Jupyter Notebook",
    "href": "https://github.com/vitoUwu/dio-lab-open-source",
    "isFork": true
  },
  "FileUploader": {
    "name": "FileUploader",
    "description": "A file uploader API made with ASP.NET ",
    "language": "C#",
    "href": "https://github.com/vitoUwu/FileUploader",
    "isFork": false
  },
  "WebApi": {
    "name": "WebApi",
    "description": "An API made for studies on the C# and .NET 8",
    "language": "C#",
    "href": "https://github.com/vitoUwu/WebApi",
    "isFork": false
  },
  "starting": {
    "name": "starting",
    "description": "Powered by deco.cx",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/starting",
    "isFork": true
  },
  "storefront": {
    "name": "storefront",
    "description": "Powered by deco.cx",
    "language": null,
    "href": "https://github.com/vitoUwu/storefront",
    "isFork": true
  },
  "vscode-timer": {
    "name": "vscode-timer",
    "description": "A Visual Studio Code Extension to monitor how long you have been coding for.",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/vscode-timer",
    "isFork": true
  },
  "agent": {
    "name": "agent",
    "description": null,
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/agent",
    "isFork": true
  },
  "Airhorn": {
    "name": "Airhorn",
    "description": "A Discord bot made with go",
    "language": "Go",
    "href": "https://github.com/vitoUwu/Airhorn",
    "isFork": false
  },
  "memonote": {
    "name": "memonote",
    "description": "Memonote is an app designed for people who are brilliant. Write down your ideas, stories, checklists and have everything synced",
    "language": "Svelte",
    "href": "https://github.com/vitoUwu/memonote",
    "isFork": false
  },
  "notification-service": {
    "name": "notification-service",
    "description": null,
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/notification-service",
    "isFork": false
  },
  "FSMP": {
    "name": "FSMP",
    "description": "A Discord bot used in a private server to display informations about a minecraft server",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/FSMP",
    "isFork": false
  },
  "NamedVillagers": {
    "name": "NamedVillagers",
    "description": "A simple spigot plugin that generate names for villagers and announce when they dies",
    "language": "Java",
    "href": "https://github.com/vitoUwu/NamedVillagers",
    "isFork": false
  },
  "go-api": {
    "name": "go-api",
    "description": "Study purpose repo",
    "language": "Go",
    "href": "https://github.com/vitoUwu/go-api",
    "isFork": false
  },
  "tiny-tales": {
    "name": "tiny-tales",
    "description": "Tiny Tales is a place where you can post tiny texts.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/tiny-tales",
    "isFork": false
  },
  "boracodar": {
    "name": "boracodar",
    "description": "Toda quarta-feira um novo desafio é lançado, nesse evento são apresentadas propostas de projetos toda semana para praticarmos e aprimorarmos.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/boracodar",
    "isFork": false
  },
  "Flutter-Task-App": {
    "name": "Flutter-Task-App",
    "description": "A task app created with flutter",
    "language": "Dart",
    "href": "https://github.com/vitoUwu/Flutter-Task-App",
    "isFork": false
  },
  "Vitter": {
    "name": "Vitter",
    "description": "Vitter is an application inspired by Twitter.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/Vitter",
    "isFork": false
  },
  "YottaBot": {
    "name": "YottaBot",
    "description": "A levelling and moderation focused Discord bot",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/YottaBot",
    "isFork": true
  },
  "Awesome-Profile-README-templates": {
    "name": "Awesome-Profile-README-templates",
    "description": "A collection of awesome readme templates to display on your profile",
    "language": null,
    "href": "https://github.com/vitoUwu/Awesome-Profile-README-templates",
    "isFork": true
  },
  "copa-nlw": {
    "name": "copa-nlw",
    "description": "Copa NLW é um projeto desenvolvido no evento da Rocketseat, onde usamos Next.js, React Native e Typescript ",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/copa-nlw",
    "isFork": false
  },
  "what-to-watch": {
    "name": "what-to-watch",
    "description": "What to Watch é um site onde você pode encontrar filmes novos ou até mesmo lembrar de filmes antigos! Perfeito para pessoas indecisas que ainda não sabem o que assistir.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/what-to-watch",
    "isFork": false
  },
  "apuracoes-2022": {
    "name": "apuracoes-2022",
    "description": "Projeto feito para acompanhar as apurações das eleições brasileiras de 2022.",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/apuracoes-2022",
    "isFork": false
  },
  "ignite-lab-design-system": {
    "name": "ignite-lab-design-system",
    "description": " Um projeto desenvolvido nos 3 dias de evento do Ignite Lab 03 desenvolvido pela Rocketseat, onde o objetivo era aprender Design System, funcionalidades do Figma e do Storybook.",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/ignite-lab-design-system",
    "isFork": false
  },
  "esports-nlw": {
    "name": "esports-nlw",
    "description": "Rocketseat | Next Level Week - React, React Native, TypeScript",
    "language": "TypeScript",
    "href": "https://github.com/vitoUwu/esports-nlw",
    "isFork": false
  },
  "PT-NO-Discord-Resources-Wiki": {
    "name": "PT-NO-Discord-Resources-Wiki",
    "description": "For Portuguese & Norwegian Translators — Constantly updated list of the most useful Discord Resources.",
    "language": null,
    "href": "https://github.com/vitoUwu/PT-NO-Discord-Resources-Wiki",
    "isFork": true
  },
  "Discord-bot-template": {
    "name": "Discord-bot-template",
    "description": "Um simples template para criar bots no discord",
    "language": "JavaScript",
    "href": "https://github.com/vitoUwu/Discord-bot-template",
    "isFork": false
  },
  "Python-TUI-Game": {
    "name": "Python-TUI-Game",
    "description": "A simple terminal-based game",
    "language": "Python",
    "href": "https://github.com/vitoUwu/Python-TUI-Game",
    "isFork": false
  }
};